"""Typed investigation concepts — stable structured investigation requirements."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class InvestigationConcept:
    code: str
    action: str
    reason: str
    expected_evidence: str | None

    priority: str  # critical, high, medium, low
    blocking: bool

    prerequisites: list[str] = field(default_factory=list)
    source_capabilities: list[str] = field(default_factory=list)

    triggered_by: list[str] = field(default_factory=list)
    scenario: str = "generic"

    skip_when: list[str] = field(default_factory=list)
    complete_when: list[str] = field(default_factory=list)
    conflicts_with: list[str] = field(default_factory=list)
    merge_group: str | None = None


GENERIC_CONCEPTS: list[InvestigationConcept] = [
    InvestigationConcept(
        code="generic.capture_request_id",
        action="Record the request ID from request or response headers.",
        reason="Needed to correlate the request with server-side logs.",
        expected_evidence="Request ID (x-request-id header value).",
        priority="critical", blocking=True,
        source_capabilities=["authentication"],
        scenario="generic",
        complete_when=["request_id_present"],
        merge_group="request_capture",
    ),
    InvestigationConcept(
        code="generic.capture_timestamp",
        action="Record the request timestamp or approximate time.",
        reason="Helps locate the request in time-based logs.",
        expected_evidence="ISO-8601 timestamp or approximate UTC time.",
        priority="medium", blocking=False,
        scenario="generic",
        merge_group="request_capture",
    ),
    InvestigationConcept(
        code="generic.capture_complete_request",
        action="Collect the complete request payload including all headers and body.",
        reason="Required to verify which fields were sent.",
        expected_evidence="Full HTTP request including method, URL, headers, and body.",
        priority="high", blocking=True,
        source_capabilities=["authentication"],
        scenario="generic",
        complete_when=["request_body_present", "http_method_present"],
        merge_group="request_capture",
    ),
    InvestigationConcept(
        code="generic.capture_complete_response",
        action="Collect the complete response including status code, headers, and body.",
        reason="The response body contains error details necessary for diagnosis.",
        expected_evidence="Full HTTP response including status, headers, and body.",
        priority="high", blocking=True,
        scenario="generic",
        complete_when=["response_status_present", "response_body_present"],
        merge_group="response_capture",
    ),
    InvestigationConcept(
        code="generic.confirm_expected_behavior",
        action="Confirm with the customer what they expected to happen.",
        reason="Clarifies the gap between intended and actual outcomes.",
        expected_evidence="Customer's description of expected behavior.",
        priority="medium", blocking=False,
        scenario="generic",
        complete_when=["expected_behavior_present"],
    ),
    InvestigationConcept(
        code="generic.confirm_actual_behavior",
        action="Confirm with the customer what actually occurred.",
        reason="Clarifies the actual outcome observed.",
        expected_evidence="Customer's description of actual behavior.",
        priority="medium", blocking=False,
        scenario="generic",
        complete_when=["actual_behavior_present"],
    ),
    InvestigationConcept(
        code="generic.verify_authentication",
        action="Verify the authentication credentials are valid and not expired.",
        reason="Invalid or expired credentials cause 401 errors.",
        expected_evidence="Authentication token validity and expiry status.",
        priority="low", blocking=False,
        source_capabilities=["authentication"],
        scenario="generic",
        skip_when=["status_2xx_application_response"],
    ),
    InvestigationConcept(
        code="generic.verify_endpoint_and_method",
        action="Confirm the endpoint URL and HTTP method match the documented API.",
        reason="Incorrect endpoint or method causes 404 or 405 errors.",
        expected_evidence="Comparison of used endpoint/method against documentation.",
        priority="high", blocking=True,
        merge_group="endpoint_verification",
        complete_when=["endpoint_present", "http_method_present"],
        scenario="generic",
    ),
    InvestigationConcept(
        code="generic.reproduce_minimal_request",
        action="Reproduce the issue with a minimal valid request payload.",
        reason="Isolates the problematic field or configuration.",
        expected_evidence="Minimal request payload that succeeds or shows the same error.",
        priority="medium", blocking=False,
        scenario="generic",
        merge_group="minimal_reproduction",
        skip_when=["issue_reliably_reproducible"],
    ),
    InvestigationConcept(
        code="generic.verify_final_state",
        action="Verify the final state of the affected resource.",
        reason="Confirm whether the operation ultimately produced the expected result.",
        expected_evidence="Current state of the customer, contract, usage record, or invoice.",
        priority="high", blocking=True,
        scenario="generic",
        merge_group="final_state",
    ),
    InvestigationConcept(
        code="generic.prepare_escalation",
        action="If unresolved, escalate with complete investigation evidence.",
        reason="Engineering requires identifiers, timestamps, payloads, and findings.",
        expected_evidence="Complete investigation report with ticket, evidence, findings, documentation links.",
        priority="high", blocking=False,
        scenario="generic",
        merge_group="engineering_escalation",
    ),
]

CONTRACT_CONCEPTS: list[InvestigationConcept] = [
    InvestigationConcept(
        code="contract.verify_endpoint",
        action="Confirm the endpoint is POST /v1/contracts/create.",
        reason="Ensures the request targets the correct API resource.",
        expected_evidence="Comparison of used endpoint against documentation.",
        priority="high", blocking=True,
        source_capabilities=["contract_creation"],
        merge_group="endpoint_verification",
        scenario="contracts",
    ),
    InvestigationConcept(
        code="contract.validate_required_fields",
        action="Compare the request body required fields against the documented contract creation fields.",
        reason="Missing required fields cause 400 errors.",
        expected_evidence="Comparison of request fields against documented required fields.",
        priority="critical", blocking=True,
        source_capabilities=["contract_creation"],
        triggered_by=["finding.contract-required-fields.failed", "status_400"],
        scenario="contracts",
    ),
    InvestigationConcept(
        code="contract.validate_starting_at",
        action="Validate that starting_at is a well-formed ISO-8601 timestamp.",
        reason="Invalid timestamp formats cause 400 errors.",
        expected_evidence="Confirmation that starting_at uses ISO-8601 format.",
        priority="high", blocking=True,
        source_capabilities=["contract_creation"],
        triggered_by=["status_400", "finding.contract-required-fields.failed"],
        skip_when=["starting_at_valid_format"],
        scenario="contracts",
    ),
    InvestigationConcept(
        code="contract.verify_customer_reference",
        action="Verify that the referenced customer_id exists and is active.",
        reason="An unknown or archived customer prevents contract creation.",
        expected_evidence="Customer retrieval confirming existence and active status.",
        priority="high", blocking=True,
        source_capabilities=["contract_creation"],
        merge_group="customer_reference",
        scenario="contracts",
    ),
    InvestigationConcept(
        code="contract.verify_rate_card_reference",
        action="Verify that any referenced rate card or product exists and is active.",
        reason="An unknown or archived rate card prevents contract creation.",
        expected_evidence="Rate card or product retrieval confirming existence.",
        priority="medium", blocking=False,
        source_capabilities=["rate_card_configuration"],
        merge_group="pricing_reference",
        scenario="contracts",
    ),
    InvestigationConcept(
        code="contract.capture_uniqueness_key",
        action="Record the uniqueness_key from the request.",
        reason="409 responses often involve uniqueness-key conflicts.",
        expected_evidence="The uniqueness_key value from the request body.",
        priority="critical", blocking=True,
        triggered_by=["finding.contract-uniqueness-key-present.passed", "status_409"],
        complete_when=["uniqueness_key_recorded"],
        scenario="contracts",
    ),
    InvestigationConcept(
        code="contract.determine_retry_intent",
        action="Determine whether this request is a retry of a previous logical operation.",
        reason="The handling of a 409 depends on whether the operation was already attempted.",
        expected_evidence="Customer confirmation of retry versus new operation intent.",
        priority="critical", blocking=True,
        prerequisites=["contract.capture_uniqueness_key"],
        triggered_by=["status_409"],
        scenario="contracts",
    ),
    InvestigationConcept(
        code="contract.locate_previous_operation",
        action="Use the uniqueness_key to locate the earlier request that consumed it.",
        reason="The original request may have already created the contract successfully.",
        expected_evidence="Original request ID, timestamp, and result from server logs or API.",
        priority="critical", blocking=True,
        prerequisites=["contract.capture_uniqueness_key"],
        source_capabilities=["idempotency"],
        triggered_by=["status_409"],
        scenario="contracts",
    ),
    InvestigationConcept(
        code="contract.inspect_previous_result",
        action="Inspect the result of the original operation.",
        reason="If the original succeeded, the contract already exists.",
        expected_evidence="HTTP status, response body, and created contract details from original request.",
        priority="critical", blocking=True,
        prerequisites=["contract.locate_previous_operation"],
        source_capabilities=["idempotency"],
        triggered_by=["status_409"],
        scenario="contracts",
    ),
    InvestigationConcept(
        code="contract.retrieve_existing_contract",
        action="Retrieve the existing contract if the original operation created one.",
        reason="The existing contract may already satisfy the intended outcome.",
        expected_evidence="Contract details including customer_id, starting_at, rate card, and status.",
        priority="high", blocking=True,
        prerequisites=["contract.inspect_previous_result"],
        source_capabilities=["contract_retrieval"],
        triggered_by=["status_409"],
        scenario="contracts",
    ),
    InvestigationConcept(
        code="contract.compare_existing_pricing",
        action="Compare existing contract pricing and rate card with intended configuration.",
        reason="Ensure the contract has the correct pricing model.",
        expected_evidence="Comparison of existing contract rate card with intended rate card.",
        priority="high", blocking=False,
        prerequisites=["contract.retrieve_existing_contract"],
        source_capabilities=["contract_retrieval", "rate_card_configuration"],
        merge_group="pricing_reference",
        triggered_by=["status_409"],
        scenario="contracts",
    ),
    InvestigationConcept(
        code="contract.decide_key_reuse",
        action="Decide whether to reuse the same uniqueness_key or generate a new one.",
        reason="The same key should be reused only for the same logical retry.",
        expected_evidence="Decision and rationale for key reuse or replacement.",
        priority="high", blocking=True,
        prerequisites=["contract.retrieve_existing_contract"],
        source_capabilities=["idempotency"],
        triggered_by=["status_409"],
        scenario="contracts",
    ),
    InvestigationConcept(
        code="contract.prepare_escalation",
        action="If unresolved, escalate with request ID, uniqueness_key, and reproduction evidence.",
        reason="Engineering needs identifiers, timestamps, and operation evidence.",
        expected_evidence="Complete investigation report with contract-specific evidence.",
        priority="high", blocking=False,
        source_capabilities=["idempotency"],
        merge_group="engineering_escalation",
        scenario="contracts",
    ),
]

USAGE_CONCEPTS: list[InvestigationConcept] = [
    InvestigationConcept(
        code="usage.capture_transaction_id",
        action="Record the transaction_id from the request.",
        reason="The transaction_id is required to locate the event in Event Search.",
        expected_evidence="Transaction ID value from the request body.",
        priority="critical", blocking=True,
        triggered_by=["scenario.usage_ingestion"],
        complete_when=["transaction_id_present"],
        scenario="usage",
    ),
    InvestigationConcept(
        code="usage.search_event",
        action="Use the transaction_id to locate the event in Event Search.",
        reason="Event Search confirms ingestion status and shows matched customer, billable metric, and properties.",
        expected_evidence="Event Search API response showing the ingested event.",
        priority="critical", blocking=True,
        prerequisites=["usage.capture_transaction_id"],
        source_capabilities=["event_search"],
        triggered_by=["scenario.usage_ingestion"],
        scenario="usage",
    ),
    InvestigationConcept(
        code="usage.verify_customer_match",
        action="Verify the event was matched to the intended customer or ingest alias.",
        reason="A customer mismatch routes usage to the wrong account.",
        expected_evidence="Event Search result showing matched customer or alias.",
        priority="high", blocking=True,
        prerequisites=["usage.search_event"],
        triggered_by=["scenario.usage_ingestion"],
        scenario="usage",
    ),
    InvestigationConcept(
        code="usage.verify_billable_metric_match",
        action="Verify the event was matched to a billable metric.",
        reason="Events not matching any billable metric are not billed.",
        expected_evidence="Event Search result showing matched billable metric ID or none.",
        priority="critical", blocking=True,
        prerequisites=["usage.search_event"],
        source_capabilities=["billable_metric_configuration"],
        triggered_by=["scenario.usage_ingestion"],
        scenario="usage",
    ),
    InvestigationConcept(
        code="usage.compare_event_type",
        action="Compare the event_type against the billable metric's event filter.",
        reason="Mismatched event_type prevents the event from being matched.",
        expected_evidence="Comparison of event_type with the billable metric event_type filter.",
        priority="critical", blocking=True,
        prerequisites=["usage.verify_billable_metric_match"],
        source_capabilities=["billable_metric_configuration"],
        triggered_by=["scenario.usage_ingestion"],
        scenario="usage",
    ),
    InvestigationConcept(
        code="usage.compare_property_filters",
        action="Compare event property names against the billable metric property filters.",
        reason="Property name mismatches prevent usage from being counted.",
        expected_evidence="Comparison of event properties with billable metric property filters.",
        priority="critical", blocking=True,
        prerequisites=["usage.verify_billable_metric_match"],
        source_capabilities=["billable_metric_configuration"],
        triggered_by=["scenario.usage_ingestion"],
        scenario="usage",
    ),
    InvestigationConcept(
        code="usage.compare_aggregation_key",
        action="Verify the aggregation key exists in the event properties and value type is valid.",
        reason="Missing or invalid aggregation key prevents usage from being aggregated.",
        expected_evidence="Confirmation of aggregation key presence and valid value type.",
        priority="critical", blocking=True,
        prerequisites=["usage.verify_billable_metric_match"],
        source_capabilities=["billable_metric_configuration"],
        triggered_by=["scenario.usage_ingestion"],
        scenario="usage",
    ),
    InvestigationConcept(
        code="usage.verify_active_contract",
        action="Verify the customer has an active contract that covers the relevant product.",
        reason="Usage is only billed when it matches an active rate card under an active contract.",
        expected_evidence="Customer contract details showing status and covered products.",
        priority="high", blocking=True,
        prerequisites=["usage.verify_customer_match"],
        source_capabilities=["contract_retrieval"],
        triggered_by=["scenario.usage_ingestion"],
        scenario="usage",
    ),
    InvestigationConcept(
        code="usage.verify_active_rate_card",
        action="Verify the rate card associated with the contract is active.",
        reason="Inactive rate cards do not generate usage charges.",
        expected_evidence="Rate card details showing active status and product coverage.",
        priority="high", blocking=True,
        prerequisites=["usage.verify_active_contract"],
        source_capabilities=["rate_card_configuration"],
        triggered_by=["scenario.usage_ingestion"],
        scenario="usage",
    ),
    InvestigationConcept(
        code="usage.verify_invoice_period",
        action="Verify the event timestamp falls within the expected invoice period.",
        reason="Events outside the billing period may not appear on the expected invoice.",
        expected_evidence="Comparison of event timestamp with invoice billing period.",
        priority="high", blocking=False,
        source_capabilities=["invoice_verification"],
        triggered_by=["scenario.usage_ingestion"],
        scenario="usage",
    ),
    InvestigationConcept(
        code="usage.locate_original_transaction",
        action="Locate the original transaction that used the same transaction_id.",
        reason="HTTP 409 on ingest means the transaction_id was already consumed.",
        expected_evidence="Event Search result for the original transaction.",
        priority="critical", blocking=True,
        prerequisites=["usage.capture_transaction_id"],
        source_capabilities=["event_search"],
        triggered_by=["status_409"],
        scenario="usage",
    ),
    InvestigationConcept(
        code="usage.compare_original_and_retry",
        action="Compare the original and retry event payloads.",
        reason="Determines whether the retry represents the same logical event.",
        expected_evidence="Side-by-side comparison of original and retry payload fields.",
        priority="high", blocking=True,
        prerequisites=["usage.locate_original_transaction"],
        triggered_by=["status_409"],
        scenario="usage",
    ),
    InvestigationConcept(
        code="usage.determine_same_logical_event",
        action="Determine whether the duplicate represents the same logical event.",
        reason="If yes, the original result is already valid.",
        expected_evidence="Decision and rationale based on payload comparison.",
        priority="high", blocking=True,
        prerequisites=["usage.compare_original_and_retry"],
        source_capabilities=["idempotency"],
        triggered_by=["status_409"],
        scenario="usage",
    ),
    InvestigationConcept(
        code="usage.prepare_escalation",
        action="If unresolved, escalate with transaction ID, customer ID, metric ID, Event Search results.",
        reason="Engineering needs complete usage-ingestion evidence.",
        expected_evidence="Complete investigation report with usage-specific evidence.",
        priority="high", blocking=False,
        merge_group="engineering_escalation",
        scenario="usage",
    ),
]

CUSTOMER_CONCEPTS: list[InvestigationConcept] = [
    InvestigationConcept(
        code="customer.validate_required_fields",
        action="Compare the request body against documented required customer fields.",
        reason="Missing required fields (e.g., name) cause 400 errors.",
        expected_evidence="Comparison of request fields against documented required fields.",
        priority="critical", blocking=True,
        source_capabilities=["contract_creation"],
        triggered_by=["finding.customer-required-fields.failed"],
        scenario="customers",
    ),
    InvestigationConcept(
        code="customer.search_existing_customer",
        action="Search for an existing customer with the same external identifier or ingest alias.",
        reason="Duplicate identifiers cause 409 errors.",
        expected_evidence="Customer search results filtered by external_id or ingest alias.",
        priority="critical", blocking=True,
        source_capabilities=["contract_retrieval"],
        scenario="customers",
    ),
    InvestigationConcept(
        code="customer.compare_existing_identifiers",
        action="Compare the existing customer's identifiers with the intended identifiers.",
        reason="Determines whether this is a duplicate or a genuinely new customer.",
        expected_evidence="Comparison of existing customer external_id/ingest alias with request.",
        priority="high", blocking=True,
        prerequisites=["customer.search_existing_customer"],
        scenario="customers",
    ),
    InvestigationConcept(
        code="customer.verify_customer_mapping",
        action="Verify the customer was created or mapped correctly.",
        reason="Confirms the customer record is usable.",
        expected_evidence="Customer retrieval showing correct name, external_id, and ingest alias.",
        priority="high", blocking=True,
        source_capabilities=["contract_retrieval"],
        merge_group="final_state",
        scenario="customers",
    ),
    InvestigationConcept(
        code="customer.prepare_escalation",
        action="If unresolved, escalate with customer identifiers and search results.",
        reason="Engineering needs customer creation evidence.",
        expected_evidence="Complete investigation report with customer-specific evidence.",
        priority="high", blocking=False,
        merge_group="engineering_escalation",
        scenario="customers",
    ),
]

ALL_CONCEPTS = GENERIC_CONCEPTS + CONTRACT_CONCEPTS + USAGE_CONCEPTS + CUSTOMER_CONCEPTS